### ISSUE TITLE
Files not found

### ISSUE THREAD

**Issue by igorissen** [Epharmix/Toureiro#3]
Hi,

I have an issue with some files not found `toureiro.css` and `app.js` each time I go to the home page `https://my.domain.com/toureiro` 

![screenshoot](http://s8.postimg.org/fo18oeqet/Screen_Shot_2016_04_04_at_09_24_22.png)

```js
var http = require("http");

var toureiro = require("toureiro"),
    express  = require("express");

var app = express();

app.use("/toureiro", toureiro({
  redis: {
    host: "my.host.com",
    port: 10600,
    auth_pass: "my_password"
  }
}));

exports.start = start;
exports.stop = stop;

function start(callback) {
  server = http.createServer(app);

  server.listen(1338, function (err) {
    if ( err ) return callback(err);

    console.log("Toureiro is now listening at port 1338...");

    callback();
  });
}

function stop(callback) { server.close(callback); }
```

Any idea ?

**Comment by igorissen** [comment]
When using the other method

```js
// ... ... ...

var app = toureiro({
    redis: {
      host: "my.host.com",
      port: 10600,
      auth_pass: "my_password"
    }
  });

// ... ... ...
```

It's working great now.

**Comment by evanhuang8** [comment]
Sorry was a bit swamped at work.

I think the problem is the static url prefix. Currently the static assets are referenced as follows:

`static/css/toureiro.css`

If you mount it to a different path, it might have concated it wrong.

Can you check what the full urls for the files that are 404 are?

**Comment by igorissen** [comment]
It's ok, same here.

* app.js --> `http://localhost:1338/static/js/app.js`
* toureiro.css --> `http://localhost:1338/static/css/toureiro.css`

**Comment by igorissen** [comment]
It's like you said

> I think the problem is the static url prefix. Currently the static assets are referenced as follows:
> `static/css/toureiro.css`
> If you mount it to a different path, it might have concated it wrong.

Working codes

```js
// ... ... ...

var app = toureiro({
    redis: {
      host: "my.host.com",
      port: 10600,
      auth_pass: "my_password"
    }
  });

// ... ... ...

var app = express();

app.use("/", toureiro({
  redis: {
    host: "my.host.com",
    port: 10600,
    auth_pass: "my_password"
  }
}));

// ... ... ...
```

Not working codes

```js
// ... ... ...

var app = express();

app.use("/toureiro", toureiro({
  redis: {
    host: "my.host.com",
    port: 10600,
    auth_pass: "my_password"
  }
}));

// ... ... ...
```

So I can say thank you for pointing it. Can you update this line  `app.use("/toureiro", toureiro());` in your documentation ?

Thank you :+1:

**Comment by evanhuang8** [comment]
Yep will do, and thanks for finding the issue!

**Comment by evanhuang8** [comment]
Hmm looking more into this, it still doesn't do what it was originally intended to do. 

I originally thought that by not prefixing the static urls with `/` it will actually play nicely with the mounting scheme that express uses, but apparently not. Ideally people can mount to whatever subpath they want it to be, and by limiting the mount to `/` doesn't fix the problem per se. I need to look more into how to make it truly reusable components.
