### ISSUE TITLE
Static paths broken

### ISSUE THREAD

**Issue by GeoffreyPlitt** [Epharmix/Toureiro#8]
I'm using the ```app.use('/toureiro', toureiro());``` approach, and when I load the web UI, it makes a bunch of requests to get CSS/etc, to paths starting with '/static' which don't exist.

Please advise, thanks.

**Comment by evanhuang8** [comment]
@GeoffreyPlitt good catch, just fixed it in 5ab75288748d1dbe56b1991f4ceb816feb2eb515, I will cut an update soon

**Comment by evanhuang8** [comment]
0.2.6 is published to npm
